[wokwi]
version = 1
firmware = 'build/neopixel_pio.hex'
elf = 'build/neopixel_pio.elf'

name = "Projeto Matriz de LEDs"
description = "Controlando LEDs usando Raspberry Pi Pico W"
microcontroller = "pico"

